### ISSUE TITLE
ATGroundAnchor does not work

### ISSUE THREAD

**Issue by allista** [allista/AT_Utils#19]
Apparently starting from the latest release. Thanks @pmborg.

**Comment by allista** [comment]
Should be fixed starting from 1.9.1

**Comment by pmborg** [comment]
Hello Aliista!, actually the problem persists if you scale the "Inflatable Ground Hangar" to size 4 for example, it just skids on the runway even with the anchor.

**Comment by allista** [comment]
If you would be so kind as to re-test it with the latest version?
In my experience lately there's no problem with the anchor, even with very heavy hangars.

**Comment by pmborg** [comment]
> 
> 
> If you would be so kind as to re-test it with the latest version?
> In my experience lately there's no problem with the anchor, even with very heavy hangars.

Sure, I will test it now.

**Comment by pmborg** [comment]
Yes, true the problem is solved, I saved a video while was testing, let me know if it is useful :)

**Comment by allista** [comment]
Cool, then I close this issue.
